name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Build backend image
      - name: Build Backend Image
        run: docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/bank-backend:latest" backend/


      # Build frontend image
      - name: Build Frontend Image
        run: docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/bank-frontend:latest" frontend/

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bank-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bank-frontend:latest

      # SSH Deploy
      - name: SSH Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/app/blockchain-banking-pqc
            docker compose pull
            docker compose down
            docker compose up -d
